version: "3.4"
services:
  de-hello-service-dapr:
    image: daprio/daprd:edge
    #network_mode: "host"
    command: ["./daprd",
        "-app-id", "hello-service",
        "-app-protocol", "grpc",
        "-app-port", "3000",
        "-dapr-grpc-port", "3801",
        "-dapr-http-port", "3501",
        "-enable-metrics=false",
        "-log-level", "info",
        "-placement-host-address", "de-placement:50006",
        "-components-path","/components"]
    volumes:
        - "/Users/chenliyu/go/src/dapr-examples/hello-service/components/:/components"
        - "/etc/localtime:/etc/localtime:ro"
    restart: always
    ports:
        - 3501:3501
    depends_on:
        - de-hello-service
    networks:
        - daprapp

  de-hello-service:
    image: abigfish/hello-service
    #network_mode: "host"
    environment:
        CONFIG_NAME: "config"
    volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/Users/chenliyu/go/src/dapr-examples/hello-service/config:/config"
    restart: always
    ports:
        - 3000:3000
    depends_on:
        - de-redis
        - de-placement
    networks:
        - daprapp
  de-redis:
      image: "redis:latest"
      ports:
        - "6380:6379"
      networks:
        - daprapp
  de-placement:
      image: "daprio/dapr:1.6.0"
      command: ["./placement", "-port", "50006"]
      ports:
        - "50006:50006"
      networks:
        - daprapp
networks:
  daprapp:
    external: true