server:
    name: de-hello-service
    address: :3000
database:
    type: mysql
    host: docker.for.mac.host.internal
    port: 3306
    user: root
    password: 123456
    name: de-hello-service
    charset: utf8mb4
    prefix: t_ # 表前缀
    max-idle: 10 # 连接池最大闲置的连接数
    max-open: 10 # 连接池最大打开的连接数
    max-lifetime: 30 #连接对象可重复使用的时间长度(秒)
    debug: false # 是否开启 sql 调试模式